//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRRelatorios.Rel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DRRelatorios.Rel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kghostview {
            get {
                object obj = ResourceManager.GetObject("kghostview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção,
        ///
        ///O sistema identificou que existem despesas que não foram classificadas Etapa ou Atividades não informada, ou despesa não aprovada).
        ///
        ///Para que as informações do relatório e os valores das despesas sejam processados corretamente é importante que todas as despesas estejam devidamente classificadas.
        ///
        ///Para conferir marque a opção “Mostrar somente despesas não classificadas.” e clique em visualizar relatório..
        /// </summary>
        internal static string SMensagemValidacaoDespNaoClassificada {
            get {
                return ResourceManager.GetString("SMensagemValidacaoDespNaoClassificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção,
        ///
        ///O sistema identificou que existem despesas que não foram classificadas (Etapa ou Atividades não informada, ou despesa não aprovada).
        ///
        ///Para que as informações do relatório e os valores das despesas sejam processados corretamente é importante que todas as despesas estejam devidamente classificadas.
        ///
        ///Para conferir acesse o relatório “Despesa Por Etapa/Atividade” e marque a opção “Mostrar somente despesas não classificadas.” e clique em visualizar relatório..
        /// </summary>
        internal static string SMensagemValidacaoDespNaoClassificada2 {
            get {
                return ResourceManager.GetString("SMensagemValidacaoDespNaoClassificada2", resourceCulture);
            }
        }
    }
}
