CREATE TABLE [DBO].[DRPERMISSAOUSER](
	[IDUSUARIO] [INT] NOT NULL,
	[IDSEGURANCA] [INT] NOT NULL,
	[SEGURANCA] [NCHAR](50) NULL,
 CONSTRAINT [PK_DRPERMISSAOUSER] PRIMARY KEY CLUSTERED 
(
	[IDUSUARIO],[IDUSUARIO]
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [DBO].[DRPERMISSAOUSER]  WITH CHECK ADD  CONSTRAINT [FK_DRETAPA_DRPROJETO] FOREIGN KEY([IDUSUARIO])
REFERENCES [DBO].[DRUSUARIO] ([IDUSUARIO])

GO
