SELECT CODETAPA CODIGO,DESCRICAO,
(SELECT MIN(DATAINI) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ  
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%') DATAINI,
(SELECT MAX(DATATERMINO) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ 
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%') DATATERMINO,
 '' UNIDADE,
 0.00 QTD,
 (SELECT ISNULL( SUM( ISNULL(PrecoUnitarioMaterial,0) * ISNULL(QTD,0) ),0) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND QTD > 0 
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%') PRECOUNITARIOMATERIAL,
 (SELECT ISNULL( SUM(ISNULL(PrecoUnitarioMaoObra,0) * ISNULL(QTD,0) ),0) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND QTD > 0 
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%') PRECOUNITARIOMAOOBRA,
 (SELECT ISNULL( SUM(TOTALGERAL),0) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND QTD > 0 
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%') TOTALGERAL,
 (SELECT ISNULL( SUM(VALOR),0) FROM DRDESPESA WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND STATUS='A'
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%' AND DATAPAG <= @2) DESPESAANTERIOR,
 (SELECT ISNULL( SUM(VALOR),0) FROM DRDESPESA WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND STATUS='A'
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%' AND (DATAPAG > @2 AND DATAPAG <=@3 )) DESPESAATUAL, 0.00 TOTALDESPESA              
 FROM DRETAPA               
 WHERE CODIGOPRJ =@1 AND
(SELECT ISNULL( SUM(TOTALGERAL),0) FROM DRATIVIDADE WHERE CODIGOPRJ= DRETAPA.CODIGOPRJ AND QTD > 0 
 AND CODETAPA LIKE DRETAPA.CODETAPA +'%')  > 0
UNION ALL               
SELECT CODATIVIDADE CODIGO,DESCRICAO,DATAINI,DATATERMINO,UNIDADE,QTD,PRECOUNITARIOMATERIAL,
PRECOUNITARIOMAOOBRA,TOTALGERAL,
(SELECT ISNULL( SUM(VALOR),0) FROM DRDESPESA WHERE CODIGOPRJ = DRATIVIDADE.CODIGOPRJ 
AND CODATIVIDADE = DRATIVIDADE.CODATIVIDADE AND  DATAPAG <= @2) DESPESAANTERIOR,
(SELECT ISNULL( SUM(VALOR),0) FROM DRDESPESA WHERE CODIGOPRJ = DRATIVIDADE.CODIGOPRJ 
AND CODATIVIDADE = DRATIVIDADE.CODATIVIDADE AND (DATAPAG > @2 AND DATAPAG <=@3 )) DESPESAATUAL, 0.00 TOTALDESPESA              
FROM DRATIVIDADE (NOLOCK) WHERE CODIGOPRJ =@1 AND TOTALGERAL > 0
 
 
-- SELECT * FROM DRDESPESA
